# Generated by Django 3.2.25 on 2026-03-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_permissions', '0009_dbconfig_engine_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompermissions',
            options={'permissions': (('entrar_finanzas', 'Finanzas'), ('entrar_ventas', 'Ventas'), ('entrar_stock', 'Stock'), ('entrar_compras', 'Compras'), ('entrar_rrhh', 'RRHH'), ('entrar_admin', 'Admin'), ('entrar_migraciones', 'Migraciones'), ('entrar_produccion', 'Produccion'), ('informe_balancegeneral', 'Balance General'), ('informe_balancegeneralpuc', 'Balance General PUC'), ('informe_balancegeneralcomprobado', 'Balance General Comprobado'), ('informe_diario', 'Libro Diario'), ('informe_mayorcuenta', 'Libro Mayor de Cuenta'), ('informe_ordenpago', 'Ordenes de Pago'), ('informe_mayorcuentaauxiliar', 'Libro Mayor de Auxiliares'), ('informe_ventascomprobante', 'Ventas por Comprobante'), ('informe_extractocuenta', 'Extracto de Cuenta Bancaria'), ('informe_centrocostos', 'Centro de Costos'), ('informe_bienactivo', 'Bien Activo'), ('informe_flujofondo', 'Flujo de Fondo'), ('informe_ordencompra', 'Orden de Compra'), ('informe_compras', 'Compras'), ('informe_saldosproveedores', 'Saldo a Proveedores'), ('informe_fondofijo', 'Fondo Fijo'), ('informe_gastosrendir', 'Rendicion de Gastos'), ('informe_comprasestadisticos', 'Estadisticos de Compras'), ('informe_presupuesto', 'Presupuestos'), ('informe_cuentascobrar', 'Cuentas por Cobrar'), ('informe_recaudaciones', 'Recaudaciones'), ('informe_ventaestadisticos', 'Estadisticos de Ventas'), ('informe_legajos', 'Legajos'), ('informe_sueldosjornales', 'Sueldos y Jornales'), ('informe_anticipos', 'Anticipos'), ('informe_aguinaldos', 'Aguinaldos'), ('informe_recibos', 'Recibos'), ('informe_articulos', 'General de Productos'), ('informe_depositos', 'Existencias por Depositos'), ('informe_valorizado', 'Existencias valorizadas'), ('informe_precios', 'Control de Precios'))},
        ),
        migrations.AlterField(
            model_name='dbconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
