"""
Django settings for multisoft_informes project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATICFILES_DIRS = [os.path.join(os.path.join(BASE_DIR, 'static'))]
STATIC_ROOT = os.path.join(os.path.join(BASE_DIR, 'staticfiles'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w#@8h=qh07b46fup8sh3j@ly+u-*_4xhljl+dn6ojbw!r0fk+3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django_admin_bootstrapped',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'dajaxice',
    'custom_permissions',
    'finanzas',
    'ventas'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'multisoft_informes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(os.path.join(BASE_DIR, 'templates')),
                 'django.template.loaders.filesystem.Loader',
                 'django.template.loaders.app_directories.Loader'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'multisoft_informes.wsgi.application'

ADMIN_MEDIA_PREFIX = '/static/admin/'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
#------------------------------------------------------------------------------ 
#----------------------------------------------------------------- DATABASES = {
   #-------------------------------------------------------------- 'default' : {
       #--------------------------------------------- 'ENGINE': 'sqlany_django',
       #--------------------------------------------------- 'NAME': 'integrado',
       #--------------------------------------------------------- 'USER': 'dba',
       #----------------------------------------- 'PASSWORD': 'ownlomas1415key',
       #--------------------------------------------------- 'HOST': '127.0.0.1',
       #--------------------------------------------------------- 'PORT': '2638'
   #-------------------------------------------------------------------------- }
#----------------------------------------------------------------------------- }


#----------------------------------------------------------------- DATABASES = {
   #-------------------------------------------------------------- 'default' : {
       #--------------------------------------------- 'ENGINE': 'sqlany_django',
       #-------------------------------------- 'OPTIONS': {'dsn': 'integlucas2'}
   #-------------------------------------------------------------------------- }
#----------------------------------------------------------------------------- }

#----------------------------------------------------------------- DATABASES = {
    #-------------------------------------------------------------- 'default': {
                #----------- 'ENGINE': 'django.db.backends.postgresql_psycopg2',
                #-------------------------------------------------- 'OPTIONS': {
                    #--------------------------- 'options': '-c search_path=dba'
                #------------------------------------------------------------ },
                #---------------------------------- 'NAME': 'Integrado_Informe',
                #------------------------------------------- 'USER': 'postgres',
                #--------------------------------------- 'PASSWORD': 'postgres',
                #------------------------------------------- 'HOST': '127.0.0.1'
    #------------------------------------------------------------------------- }
#----------------------------------------------------------------------------- }

#----------------------------------------------------------------- DATABASES = {
    #-------------------------------------------------------------- 'default': {
        #------------------------------- 'ENGINE': 'django.db.backends.sqlite3',
        #------------------------- 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    #------------------------------------------------------------------------- }
#----------------------------------------------------------------------------- }

DATABASES = { 'default': 
    {'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'NAME': 'multisoft_informes',
    'USER': 'postgres', 
    'PASSWORD': 'postgres', 
    'HOST': '127.0.0.1',
     } 
} 

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

FILE_CHARSET = 'utf-8'

DATE_INPUT_FORMATS = ('%d-%m-%Y','%Y-%m-%d')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
